# Generated by Django 4.2.6 on 2023-10-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
