# Generated by Django 4.2.6 on 2023-10-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='생성일'),
            preserve_default=False,
        ),
    ]
