# Generated by Django 4.2.6 on 2023-10-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omg_app', '0002_alter_aimodel_options_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='subscription_product_id',
            new_name='subscription_product',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
    ]
