# Generated by Django 4.2.5 on 2023-10-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omg_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
