# Generated by Django 4.2.6 on 2023-10-19 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("omg_app", "0003_rename_is_admin_user_is_staff"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messsage",
            new_name="Message",
        ),
    ]
