# Generated by Django 4.2.6 on 2023-10-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("omg_app", "0004_rename_messsage_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(verbose_name="상품명")),
                ("amount", models.IntegerField(default=0, verbose_name="상품 가격")),
            ],
            options={
                "verbose_name": "상품",
                "verbose_name_plural": "상품 목록",
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription_product_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="omg_app.subscriptionproduct",
                verbose_name="상품ID",
            ),
        ),
    ]
